#!/bin/bash

set -euo pipefail

function +++(){ :;}

function help()
{
    cat <<EOF
mds converts a markdown file into PDF using pandoc and latex.

Usage:

  mds [OPTIONS] MARKDOWNFILE.md

OPTIONS:
  -h          show this help
  -q          pass through quarto for executable blocks
  -d          work in draft mode; figures are included as outlines
  -s FILE|DIR where to find the *.theme file
  -t          produce a handout version
  -p          preserve the intermediate latex file that pandoc produces
  -v          verbose mode
  -vv         more verbosity
  -vvv        more verbosity and show latex output

MARKDOWNFILE.md can use extended pandoc markdown syntax.

If no FILE or DIR is given, and no MARKDOWNFILE.theme exists, one is
created, and populated with an example theme consisting of three
files: mds.theme, mds.tex, and logo.png.  These files can be edited to
change the look of the slides.

Output is written to MARKDOWNFILE.pdf or to the handout version
MARKDOWNFILE_handout.pdf.

EOF
}

function valid_theme_syntax()
{
    # only lines allowed of the form VAR=VALUE, with a few exceptions
    theme_file="$1"
    # Since this is a subset of bash syntax, let's check that first
    if ! bash -n "$theme_file"; then
        return 1
    fi
    let n=0
    cat "$theme_file" | while IFS= read -r line; do
        let n++
        linefine=true
        if [ "$line" ]; then
            # avoid subshells if we can
            line="${line//\$/\\\$}"
            line="${line//\(/\\\(}"
            line="${line//\)/\\\)}"
            line="${line//\`/\\\`}"
            eval set Z "$line" # 2>/dev/null
            if [ $? != 0 ]; then
                linefine=false;
            elif [ $# -gt 2 ]; then
                if ! [ $2 = if -a $3 = '[' -a $# = 7 ]; then
                    echo $#
                    linefine=false
                fi
            elif [ $# = 2 ]; then
                if ! [[ $2 =~ = ]]; then
                    if [ $2 != then -a $2 != fi -a $2 != else ] ; then
                        linefine=false
                    fi
                fi
            fi
        fi
        if ! $linefine; then
            echo "ERROR: Syntax error in $theme_file, line $n."
            return 1
        fi
    done
}

# Parse command line options, but don't 'echo $parsingcomment' until a -v argument has been detected.
parsingcomment="+++ Parsing command line options. +++
"

DRAFT=false
QUARTO=false
HANDOUT=false
VERBOSE=0
PRESERVELATEX=false
while getopts "s:vdqhtp" option; do
    case $option in
        "v") let VERBOSE=VERBOSE+1; function +++() { echo "+++ $@"; }; echo -n "$parsingcomment"; parsingcomment="";; # only echo the comment once
        "d") DRAFT=true;;
        "q") QUARTO=true;;
        "t") HANDOUT=true;;
        "p") PRESERVELATEX=true;;
        "s") STYLEDIR=${OPTARG};;
        "h") help; exit 0;;
    esac
done
shift $((OPTIND - 1))

+++ Checking for command line errors. +++

if [ $# = 0 ]; then
    echo "ERROR ($0): No MARKDOWNFILE command argument." 1>&2
    help
    exit 1
elif [ ! -f "$1" ]; then
    echo "ERROR ($0): File '$1' not found." 1>&2
    help 1>&2
    exit 1
else
    +++ Found file $1. +++
fi
if (( $# > 1 )); then 
    echo "ERROR ($0): Extraneous command arguments: ${@:2}." 1>&2
    help 1>&2
    exit 1
fi

+++ Check prerequisite utilities +++

which pandoc >& /dev/null || module load pandoc || exit 1
which xelatex >& /dev/null || module load texlive || exit 1
if $QUARTO; then
    if ! which quarto; then
        exit 1
    fi
fi
    
+++ Determine markdown file basename, style dir, and temporary file +++ 

NAME=${1%.*}
STYLEDIR=${STYLEDIR:-$NAME.theme}

tempfile=$(mktemp --suffix .md)
_INTERMEDIATEFILES=("$tempfile")

function cleanup()
{
    +++ Get rid off intermediates but leave latex source in case you want to tweak it +++
    for filename in ${_INTERMEDIATEFILES[@]}; do
        \rm -f "$filename"
    done
    if [ "${NAME:-}" ]; then
        if ! "$PRESERVELATEX"; then
            +++ Remove latex source too +++
            rm -f "${NAME}.tex"
            if [ -f "${realthemetex:-}" ] ; then
                rm -f "$realthemetex"
            fi
        fi
    fi   
}
trap cleanup INT TERM EXIT

+++ Starting with default theme settings. +++

HIGHLIGHT=zenburn
ASPECTRATIO=169
LOGO=""
LOGOHEIGHT=0.1
LOGOWIDTH=""
LOGOUP=""
FONTFAMILY=""
FONTSIZE=9pt
THEME=Boadilla
INNERTHEME=rounded
FONTTHEME=structurebold
COLORTHEME=orchid
THEMETEX=""
ENGINE=pdflatex


+++ Override theme settings if NAME.theme directory exists. +++

if ! [ -e "{STYLEDIR:-}" ]; then
    trythesestyledirs=("{NAME}.theme" "mds.theme" "style.theme")
    for possiblestyledir in ${trythesestyledirs[@]}; do
        if [[ -f "${possiblestyledir}" || -d "${possiblestyledir}" ]]; then
            STYLEDIR="${possiblestyledir}"
            break
        fi
    done
fi

if [ -d "$STYLEDIR" ]; then # prefered mode if having theme files in a separate dir
    +++ Found directory $STYLEDIR and looking for settings. +++
    themefile=$(find "$STYLEDIR/" -type f -name '*.theme' | head -n 1)
    if [ -f "$themefile" ]; then
        +++ Found file \""$themefile"\" and reading settings. +++
        if valid_theme_syntax "$themefile"; then
            HERE=$(dirname "$themefile") # predefine this so $HERE can be used in the themefile
            source "$themefile"
        else
            exit 1
        fi
    else
        echo "ERROR: Could not find '*theme' in $STYLEDIR." 1>&2
        exit 2
    fi
elif [ -f "$STYLEDIR" ]; then # but we accept the path to the theme file as well, then it does not need to have the .theme extension.
    +++ Found file $STYLEDIR and reading settings. +++
    if valid_theme_syntax "$STYLEDIR"; then
        HERE=$(dirname "$STYLEDIR")
        source "$STYLEDIR"
    else
        exit 1
    fi
else
    if [ -z "${STYLEDIR:-}" ]; then
        STYLEDIR=${NAME}.theme
    fi
    +++ Generating a template theme in directory \"$STYLEDIR\" +++
    mkdir -p "$STYLEDIR"
    themefile="$STYLEDIR/mds.theme"
    if [ -z "$THEMETEX" ]; then
        if ! [ -f "$STYLEDIR/mds.tex" ]; then
            THEMETEX="$STYLEDIR/mds.tex"
            echo "% THEMETEX file for mds" > "${THEMETEX}"
            echo "% additional preamble latex code can be put in this file" >> "${THEMETEX}"
            echo "\renewcommand{\sectionname}{%THEMETEX_SECTIONNAME} % sets the name to use for sections in section slides to the variable specified in mds.theme" >> "${THEMETEX}"
            THEMETEX_SECTIONNAME="Part"
        fi
    fi
    +++ Generating a logo to use +++
    base64 -d > "${STYLEDIR}/logo.png" <<EOF
iVBORw0KGgoAAAANSUhEUgAAASsAAAGyCAMAAACLExINAAAAw3pUWHRSYXcgcHJvZmlsZSB0eXBl
IGV4aWYAAHjabVBbDsMgDPvPKXaEvErDcWDtpN1gx18gqTS2WcJxE+GawPl6PuA2wKSg226lloIO
rVq5uTAMtMmEOnmCeypa+9A55ajiVWJgJSpd/bxwVWqutg8ju+egr4OqmcC+jDiKjERDH2lU00g4
BpQGLZ6Fpdr++YR+4gqLA4PU1tg/37tv79j8P8J8Cgk6i1gEkHEUpPmAnFE8lKviWsVmh9LMF/Jv
TxfgDW3wWXOdOoBLAAABfmlDQ1BJQ0MgcHJvZmlsZQAAeJx9kTtIA0EURc9ulIhGLIwgYrFFtDIi
KmKpUQiCQogRErVwP+YD2U3YTbCxFGwFCz+NUQsba20tbAVB8ANibWGlaCNhZZJAghhfM4c77z7m
3QG5lNVNp2UKTKtgR8MhJZ5YVryvdOChh2FGVN3JT0ci8zStr3skcd4FxazmfX9Wp7Hu6CApwJSe
twsgrQETG4W84H3Ar6dVA6RzYMiOJ5ZBehS6VuU3wakKy2Km345FZ0D2A0qqgbUG1tO2CfI4EDBM
ywA5XmVD8KZgM1vUa+8UG/rWraVFoQP9hJljgQgKGkUyZCkQJIOFgkOUMKEm/r6KP0IRjSwZdBRm
yWGiVvyIP/idrZMcG61O8oWg9cV1PwbAuwvlHdf9Pnbd8gl4nuHKqvtzJZj8BM9OXQscQdcWXFzX
NW0PLreh9ymv2mpF8gByMgnvZ9CZgO5baF+p5la75/QBYpswfwMHhzCYgq7VJnu3Neb2b08tvx/f
wnLStvNDVwAADXhpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/
IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRv
YmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDQuNC4wLUV4aXYyIj4KIDxyZGY6UkRGIHht
bG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAg
PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMu
YWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5j
b20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgIHhtbG5zOmRjPSJodHRwOi8vcHVy
bC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgIHhtbG5zOkdJTVA9Imh0dHA6Ly93d3cuZ2ltcC5v
cmcveG1wLyIKICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgog
ICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICB4bXBNTTpEb2N1
bWVudElEPSJnaW1wOmRvY2lkOmdpbXA6YmNmZGJhNjAtZTk1Ny00NTA3LTk3MGEtMzgyY2Y1MDJj
NzA1IgogICB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmJlNjc0NjdhLWI1ZjItNDc1My05ZTIz
LTg2YTFlNzcyYWRkNiIKICAgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjk2ZTRi
NGUwLTgwMTQtNDFkNS04ZTIxLWY1ZjM5YjY1N2IyMSIKICAgZGM6Rm9ybWF0PSJpbWFnZS9wbmci
CiAgIEdJTVA6QVBJPSIyLjAiCiAgIEdJTVA6UGxhdGZvcm09IkxpbnV4IgogICBHSU1QOlRpbWVT
dGFtcD0iMTczMDY3MDQ4MTE5MTgyNCIKICAgR0lNUDpWZXJzaW9uPSIyLjEwLjM4IgogICB0aWZm
Ok9yaWVudGF0aW9uPSIxIgogICB4bXA6Q3JlYXRvclRvb2w9IkdJTVAgMi4xMCIKICAgeG1wOk1l
dGFkYXRhRGF0ZT0iMjAyNDoxMTowM1QxNjo0ODowMS0wNTowMCIKICAgeG1wOk1vZGlmeURhdGU9
IjIwMjQ6MTE6MDNUMTY6NDg6MDEtMDU6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6
U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJzYXZlZCIKICAgICAgc3RFdnQ6
Y2hhbmdlZD0iLyIKICAgICAgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpkN2ViY2E3YS1kZjY3
LTRjNTUtOTAxZC0wNTQzNmJhNGY4NGQiCiAgICAgIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkdpbXAg
Mi4xMCAoTGludXgpIgogICAgICBzdEV2dDp3aGVuPSIyMDI0LTExLTAzVDE2OjQ4OjAxLTA1OjAw
Ii8+CiAgICA8L3JkZjpTZXE+CiAgIDwveG1wTU06SGlzdG9yeT4KICA8L3JkZjpEZXNjcmlwdGlv
bj4KIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
IAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAog
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAg
ICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0idyI/PqOrGx8AAAA2UExURXMu
bQAAAAAALwAAXwAAjyYAJjoAOk4ATv///3FxcXUAdSxEVBsbG6qqqrAAsIfP/1RUVA4WG641O9YA
AAABdFJOUwBA5thmAAAAAWJLR0QAiAUdSAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB+gL
AxUwAeEKyk4AAAOeSURBVHja7dxBjhRBFEPBLmYADUxBc//LskIIsXHmLyFRjneEkNd+PCSppedx
+57nJVLnUdGJKl8WqjxU/86qiOq4jOrTPft4mdVvqi/fbtnny3bVRXWgiqkOVDHVgSqg+jC0KqJ6
GVo1Ub3OrKqoZlZdVCOrMqqJVRvVwKqOat+qj2rbqpBq16qRatOqkmrPqpNqy6qUaseqlWrDqpZq
3aqXatmqmGrVqplq0aqaas2qm2rJqpxqxaqdasGqniq3QhVboYqtUMVWqGIrVLEVqtgKVWyFKrZC
FVuhiq1QxVaoYitUsRWq2ApVbIUqtkIVW6GKrVDFVqhiK1SxFarYClVshSq2QhVbvfV8B6xS/WWF
KrZ6omJ1AVWr1Q5Vq9XrdVZfb9uPy62+3zZWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFix
YsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWK
FStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStW
rFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFix
YsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWK
FStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStW
rFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFix
YsWKFStWrFixYsWK1djq5WC1SMUqp3qySqmOk9UyFaucilVOxSqnYpVTscqpWOVUrHIqVjkVq5yK
VU7FKqdilVOxyqlY5VSscipWORWrnIpVTsUqp2KVU7HKqVjlVKxyqnqrBap2qxWqcqslqm6rNapq
q0WqZqtVqmKrZapeq3WqWqsNqlarHapSqy2qTqs9qkqrTapGq12qQqttqj6rfao6qwFVm9WEqsxq
RNVlNaOqshpSNVlNqYqsxlQ9VnOqGqsLqGqsLqCqsxpQtVlNqMqsRlRdVjOqX1YVDamarKZURVZj
qh6rOdXjRGVYf/b2uKTzefPe398fkv7zfgJF9rNf0yeL2wAAAABJRU5ErkJggg==
EOF
    +++ Generating a theme file "$themefile" +++
    cat > "$themefile" <<-EOF
	# Theme file for mds
	# note: no spaces around the equal sign allowed!
	HIGHLIGHT=$HIGHLIGHT
	ASPECTRATIO=$ASPECTRATIO
	LOGO="\$HERE/logo.png"
	LOGOHEIGHT=$LOGOHEIGHT
	LOGOWIDTH="$LOGOWIDTH"
	LOGOUP="$LOGOUP"
	PLAINTITLE=false
	FONTFAMILY="$FONTFAMILY"
	FONTSIZE=$FONTSIZE
	THEME=$THEME
	INNERTHEME=$INNERTHEME
	FONTTHEME=$FONTTHEME
	COLORTHEME=$COLORTHEME
	THEMETEX="\$HERE/mds.tex"
	THEMETEX_SECTIONNAME="Part"
	ENGINE=$ENGINE
EOF
fi

if [ "$FONTFAMILY" ]; then
    if [ $ENGINE != xelatex ]; then
        +++ Changing engine to xelatex to support font selection. +++
    fi
    ENGINE=xelatex
fi

# map oldstyle LOGOONTITLE to the reverse in PLAINTITLE
if [ -n "${LOGOONTITLE:-}" -a -z "${PLAINTITLE:-}" ]; then
    if "$LOGOONTITLE"; then
        PLAINTITLE=false
    else
        PLAINTITLE=true
    fi
fi
if [ -z "${PLAINTITLE:-}" ]; then
    PLAINTITLE=false
fi

+++ Find latex theme template settings +++

themetexvariables=$(compgen -v|grep THEMETEX_ || true)

if (( VERBOSE > 1 )); then   
    +++ The following settings will be used: +++
    for setting in HIGHLIGHT ASPECTRATIO LOGO LOGOUP LOGOWIDTH LOGOHEIGHT PLAINTITLE FONTFAMILY FONTSIZE THEME INNERTHEME FONTTHEME COLORTHEME THEMETEX HANDOUT ENGINE NAME DRAFT VERBOSE QUARTO $themetexvariables
    do
        printf "+++ $setting\t${!setting}\n"
    done
fi

+++ Check that the settings are valid +++
+++ Check MAIN THEME +++
validTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Goettingen/Hannover/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Marburg/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
if ! [[  $validTHEMES =~ /${THEME}/ ]]; then
    echo "ERROR: Invalid THEME '$THEME'. Valid choices are:${validTHEMES//\// }" 1>&2
    exit 1
fi
+++ Check COLORTHEME +++
validCOLORTHEMES="/albatross/beaver/beetle/crane/default/dolphin/dove/fly/lily/orchid/rose/seagull/seahorse/sidebartab/structure/whale/wolverine/"
if ! [[  $validCOLORTHEMES =~ /${COLORTHEME}/ ]]; then
    echo "ERROR: Invalid COLORTHEME '$COLORTHEME'. Valid choices are:${validCOLORTHEMES//\// }" 1>&2
    exit 1
fi
+++ Check INNERTHEME +++
validINNERTHEMES="/default/circles/rectangles/rounded/inmargin/"
if ! [[  $validINNERTHEMES =~ /${INNERTHEME}/ ]]; then
    echo "ERROR: Invalid INNERTHEME '$INNERTHEME'. Valid choices are:${validINNERTHEMES//\// }" 1>&2
    exit 1
fi
+++ Check FONTTHEME +++
validFONTTHEMES="/default/professionalfonts/structurebold/structureitalicserif/structuresmallcapsserif/serif/sansserif/"
if ! [[  $validFONTTHEMES =~ /${FONTTHEME}/ ]]; then
    echo "ERROR: Invalid FONTTHEME '$FONTTHEME'. Valid choices are:${validFONTTHEMES//\// }" 1>&2
    exit 1
fi
+++ Check HIGHLIGHT +++
if [ "${HIGHLIGHT:-}" ]; then
    validHIGHLIGHTS=/$(pandoc --list-highlight-styles | tr '\r\n' '/')/
    if ! [[  $validHIGHLIGHTS =~ /${HIGHLIGHT}/ ]]; then
        echo "ERROR: Invalid HIGHLIGHT style '$HIGHLIGHT'. Valid choices are:${validHIGHLIGHTS//\// }" 1>&2
        exit 1
    fi
fi
+++ Check ASPECTRATIO +++
if [ "${ASPECTRATIO:-}" ]; then
    validASPECTRATIOS="/1610/169/149/54/43/32/"
    if ! [[  $validASPECTRATIOS =~ /${ASPECTRATIO}/ ]]; then
        echo "ERROR: Invalid ASPECTRATIO '$ASPECTRATIO'. Valid choices are:${validASPECTRATIOS//\// }" 1>&2
        exit 1
    fi
fi
+++ Check PLAINTITLE +++
if [ "${PLAINTITLE:-}" ]; then
    validPLAINTITLES="/true/false/"
    if ! [[  $validPLAINTITLES =~ /${PLAINTITLE}/ ]]; then
        echo "ERROR: Invalid value '$PLAINTITLE' for PLAINTITLE. Valid choices are:${validPLAINTITLES//\// }" 1>&2
        exit 1
    fi
fi
+++ Check LOGOHEIGHT +++
if [ "${LOGOHEIGHT:-}" ]; then
    if ! [[ $LOGOHEIGHT =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
        echo "ERROR: Invalid number '$LOGOHEIGHT' for LOGOHEIGHT." 1>&2
        exit 1
    fi
fi
+++ Check LOGOWIDTH +++
if [ "${LOGOWIDTH:-}" ]; then
    if ! [[ $LOGOWIDTH =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
        echo "ERROR: Invalid number '$LOGOWIDTH' for LOGOWIDTH." 1>&2
        exit 1
    fi
fi
+++ Check LOGOUP +++
if [ "${LOGOUP:-}" ]; then
    if ! [[ $LOGOUP =~ ^\-?[0-9]*(\.[0-9]+)?$ ]]; then
        echo "ERROR: Invalid number '$LOGOUP' for LOGOUP." 1>&2
        exit 1
    fi
fi
+++ Check LOGO +++
if [ "${LOGO:-}" ]; then
  compatibleTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
    if ! [[  $compatibleTHEMES =~ /${THEME}/ ]]; then
        echo "WARNING: THEME '$THEME' does not support a LOGO. LOGO compatible choices are:${compatibleTHEMES//\// }" 1>&2
        sleep 5
    fi
    # check existance
    if ! [ -f "$LOGO" ]; then
        echo "ERROR: Logo file '$LOGO' does not exist." 1>&2
        exit 2
    fi
fi
+++ Check FONTSIZE +++
if [ "${FONTSIZE:-}" ]; then
    validFONTSIZES="/8pt/9pt/10pt/11pt/12pt/14pt/17pt/20pt/"
    if ! [[  $validFONTSIZES =~ /${FONTSIZE}/ ]]; then
        echo "ERROR: Invalid FONTSIZE '$FONTSIZE'. Valid choices are:${validFONTSIZES//\//, }" 1>&2
        exit 1
    fi
fi
+++ Check FONTFAMILY +++
if [ "${FONTFAMILY:-}" ]; then
    validFONTFAMILIES=$(fc-list : family | tr ',' '\n' | sort -u)
    validFONTFAMILIES=/${validFONTFAMILIES//
/\/}/
    if ! [[  $validFONTFAMILIES =~ /${FONTFAMILY}/ ]]; then
        echo "ERROR: Invalid FONTFAMILY '$FONTFAMILY'. Valid choices are:${validFONTFAMILIES//\//, }" 1>&2
        exit 1
    fi
fi
+++ Check HANDOUT +++
if [ "${HANDOUT:-}" ]; then
    validHANDOUTS="/true/false/"
    if ! [[  $validHANDOUTS =~ /${HANDOUT}/ ]]; then
        echo "ERROR: Invalid value '$HANDOUT' for HANDOUT. Valid choices are:${validHANDOUTS//\// }" 1>&2
        exit 1
    fi
fi
+++ Check THEMETEX +++
if [ "${THEMETEX:-}" ]; then
    if ! [ -f "$THEMETEX" ]; then
        echo "ERROR: THEMETEX file '$THEMETEX' does not exist." 1>&2
        exit 2
    fi
fi
+++ Check ENGINE +++
if [ "${ENGINE:-}" ]; then
    validENGINES="/pdflatex/xelatex/"
    if ! [[  $validENGINES =~ /${ENGINE}/ ]]; then
        echo "ERROR: Invalid ENGINE '$ENGINE'. Valid choices are:${validENGINES//\// }" 1>&2
        exit 1
    fi
fi

if $HANDOUT; then
    +++ Append postfix because handout +++
    POSTFIX="_handout"
else
    POSTFIX=""
fi

if [ -n "$themetexvariables" ]; then
    +++ Finding catsub +++
    if which catsub >& /dev/null; then
        CATSUB=`which catsub` # trust this
    elif [ -x catsub ]; then # check for a cached version of catsub
        CATSUB="./catsub"
    elif ! [ -f catsub ]; then
        version="1.0.0"
        archive="catsub-$version.tar.gz"
        url="https://github.com/vanzonr/catsub/archive/refs/tags/v$version.tar.gz"
        sha256="f3821cf1e03788a260aa2aac5e8097ec0696bb1898cf1905f2108c8bc4d474c9"
        wget "$url" --output-document="$archive"
        if ! sha256sum --check --quiet > /dev/null <<<"$sha256 $archive"; then
            echo "ERROR: catsub v$version download checksum failed" 1>&2
            exit 3
        fi
        tar --strip-components=1 -xzf $archive catsub-$version/catsub
        \rm -f catsub-$version.tar.gz 
        CATSUB="./catsub"
    fi
    if ! [ -x "${CATSUB}" ]; then
        echo "ERROR: catsub utility required but not found" 1>&2
        exit 3
    fi
    if ! sha256sum --check --quiet <<<"14ddf5f997ca7f77ecc1254ea7946f570b0b4dfac6c9d8c47b2054cfc7f089fd  ${CATSUB}"; then
        echo "ERROR: catsub utility checksum FAILED" 1>&2
        exit 3
    fi
    +++ Replace THEMETEX variables +++
    catsubcommand="$CATSUB"
    catsubcommand="$catsubcommand $THEMETEX"
    for setting in $themetexvariables; do
        catsubcommand="$catsubcommand %$setting '${!setting}'"
    done
    realthemetex="real$(basename $THEMETEX)${POSTFIX}"
    catsubcommand="$catsubcommand > $realthemetex"
    if (( $VERBOSE > 1)); then
        echo "+++ Executing: $catsubcommand"
    fi
    eval $catsubcommand
    THEMETEX=$realthemetex
    if ! [ -f "$THEMETEX" ]; then
        echo "ERROR: temporary THEMETEX file '$THEMETEX' does not exist." 1>&2
        exit 2
    else
        +++ Generated $realthemetex +++
    fi
fi

if [ $ENGINE = xelatex ]; then
    ENGINEDRAFTMODEOPTION=--no-pdf
else
    ENGINEDRAFTMODEOPTION=-draftmode
fi

+++ "Replacing '[[..||..]]' with modern markdown column formats." +++

function replacecolumns()
{
    local tempfile=$(mktemp)
    _INTERMEDIATEFILES+=("$tempfile")
    local colcount=0
    local firstcolwidth=0
    local blockstart=":::::::{.block}"
    local blockend=":::::::"
    local line=""
    while IFS= read -r line; do
        line=$(echo "$line" | dos2unix) # should be a better way to strip ^M
        if [ $colcount = 0 ]; then
            if [ "$line" = "[[" ]; then
                colcount=1
                firstcolwidth=$colcount
                \rm -f "$tempfile"
                touch "$tempfile"
            elif [ "$line" = "[[[" ]; then
                colcount=2
                firstcolwidth=$colcount
                \rm -f "$tempfile"
                touch "$tempfile"
            elif [ "$line" = "[[[[" ]; then
                colcount=3
                firstcolwidth=$colcount
                \rm -f "$tempfile"
                touch "$tempfile"
            else
                echo "$line"
            fi
        else
            if [ "$line" = "||" ];  then
                let colcount+=1
            elif [ "$line" = "|||" ];  then
                let colcount+=2
            elif [ "$line" = "||||" ];  then
                let colcount+=3
            fi
            if [ "$line" != "]]" ];  then
                echo "$line">>"$tempfile"
            else
                local colstart=":::{.column width=0.$(((97-colcount)/colcount))}"
                local colstart2=":::{.column width=0.$((2*(97-colcount)/colcount))}"
                local colstart3=":::{.column width=0.$((3*(97-colcount)/colcount))}"
                echo "::::::columns"
                echo ":::{.column width=0.$((firstcolwidth*(97-colcount)/colcount))}"
                echo "$blockstart"
                cat "$tempfile" | while IFS= read -r line ; do
                    case "$line" in
                        "||")
                            echo "$blockend"
                            echo ":::"
                            echo "$colstart"
                            echo "$blockstart"
                            ;;
                        "|||")
                            echo "$blockend"
                            echo ":::"
                            echo "$colstart2"
                            echo "$blockstart"                                                        
                            ;;
                        "||||")
                            echo "$blockend"
                            echo ":::"
                            echo "$colstart3"
                            echo "$blockstart"
                            ;;
                        *)
                            echo "$line"
                            ;;
                    esac
                done
                echo "$blockend"
                echo ":::"
                echo "::::::"
                colcount=0
            fi
        fi
    done
}
cat "$1" | replacecolumns > "$tempfile"

+++ "Extensions for centering, highlighting, skipping lines and " +++
+++ "easy two-column layout, using placeholders BEGINCENTERLINE " +++
+++ "ENDCENTERLINE, BEGINALERT, ENDALERT, SKIPPINGLINE          " +++

sed -i \
    -e 's/->\(.*\)<-/BEGINCENTERLINE\1ENDCENTERLINE/' \
    -e 's/\*\*\*\*\([^\*]*\)\*\*\*\*/BEGINALERT\1ENDALERT/g' \
    -e 's/^[[:space:]]*\.[[:space:]]*$/SKIPPINGLINE/' \
    "$tempfile"

+++ $tempfile written. +++

+++ "Enable extra-wide lists by adding four trailing spaces." +++
+++ "Note: four trailing spaces anywhere else are already a " +++
+++ "markdown hard line break.                              " +++

perl -0777 -i -pe 's/(\ *)([\*\-\+])(\ *)([^\n]*)([^ ])     *\n\ *\n/\1\2\3\4\5    \n\1 \3&nbsp;\n/g'  "$tempfile"

+++ $tempfile updated. +++

+++ Extension to include files in source block +++
# sed command looks for at least triple backtips, a curly bace then
# anything upto the " include=", then eats the word following include,
# up to a curly closing brace further sed commands look for options
# startLine= and endLine= clauses.  These must follow the include= and
# startLine= must preceed endLine=.
sed -i.bak -e "s/\(\`\`\`\`*{\)\(.*\)\( include=\)\([^} ]*\)\(}.*\)/echo \'\1\2\5';cat \4/e"  "$tempfile"
sed -i -e "s/\(\`\`\`\`*{\)\(.*\)\( include=\)\([^} ]*\)\( startLine=\)\([^} ]*\)\(}.*\)/echo \'\1\2\7';sed -n \6,100000p \4/e"  "$tempfile"
sed -i -e "s/\(\`\`\`\`*{\)\(.*\)\( include=\)\([^} ]*\)\( endLine=\)\([^} ]*\)\(}.*\)/echo \'\1\2\7';sed -n 1,\6p \4/e"  "$tempfile"
sed -i -e "s/\(\`\`\`\`*{\)\(.*\)\( include=\)\([^} ]*\)\( startLine=\)\([^} ]*\)\( endLine=\)\([^} ]*\)\(}.*\)/echo \'\1\2\9';sed -n \6,\8p \4/e"  "$tempfile"

+++ Make pause sequence more robust by adding empty lines +++

sed -i -e "s/^\([[:space:]]*\. \. \.\)$/\n\1\n/" "$tempfile"

+++ Add theme settings in yaml header. +++

findheader=$(eval echo $(\grep -n -- '^---$' $tempfile))
tempfile2=$(mktemp)
_INTERMEDIATEFILES+=("$tempfile2")
if [[ $findheader =~ ^1:---\  ]]; then
    headerlines=$(echo ${findheader:6} | awk -F: '{print $1}')
    let insertionpoint=headerlines-1
    head -n $insertionpoint $tempfile > $tempfile2
else
    echo "---" > $tempfile2 
fi
cat >> $tempfile2 <<EOF
classoption: aspectratio=$ASPECTRATIO
fontsize: $FONTSIZE
theme: $THEME
innertheme: $INNERTHEME
fonttheme: $FONTTHEME
colortheme: $COLORTHEME
engine: knitr
keep-md: true
format: beamer
echo: true
warning: true
execute:
  cache: true
header-includes: |
 \newcommand{\setfigheight}[1]{\setkeys{Gin}{height=#1,keepaspectratio}}
 \newcommand{\setfigwidth}[1]{\setkeys{Gin}{width=#1,keepaspectratio}}
 \newcommand{\setrelfigwidth}[1]{\setfigwidth{#1\csname textwidth\endcsname}}
 \newcommand{\setrelfigheight}[1]{\setfigheight{#1\csname textheight\endcsname}}
 \usepackage{tikz}
 \usetikzlibrary{arrows.meta}
EOF
if [ "$FONTFAMILY" ]; then
    echo " \usepackage{fontspec}" >> $tempfile2
    echo " \setsansfont{$FONTFAMILY}" >> $tempfile2
fi
if [ "$LOGOUP" ]; then
    LOGOVSPACE="\vspace{$LOGOUP\textheight}"
else
    LOGOVSPACE=""
fi
if [ "$LOGO" ]; then
    if [ "$LOGOHEIGHT" ]; then
        if [ "$LOGOWIDTH" ]; then
            echo " \logo{$LOGOVSPACE\includegraphics[width=${LOGOWIDTH}\textwidth,height=${LOGOHEIGHT}\textheight]{$LOGO}}" >> $tempfile2
        else
            echo " \logo{$LOGOVSPACE\includegraphics[height=${LOGOHEIGHT}\textheight]{$LOGO}}" >> $tempfile2
        fi
    else
        if [ "$LOGOWIDTH" ]; then
            echo " \logo{$LOGOVSPACE\includegraphics[width=${LOGOWIDTH}\textwidth]{$LOGO}}" >> $tempfile2
        else
            echo " \logo{$LOGOVSPACE\includegraphics{$LOGO}}" >> $tempfile2
        fi
    fi
fi
if [ -f "$THEMETEX" ]; then
    echo " \input{$THEMETEX}" >> $tempfile2
fi
if [[ $findheader =~ ^1:---\  ]]; then
    \tail -n+$headerlines $tempfile >> $tempfile2
else
    echo "---" >> $tempfile2
    cat $tempfile >> $tempfile2
fi
\cp -f $tempfile2 $tempfile

+++ $tempfile updated. +++

if $QUARTO; then
    +++ quarto calls for execution +++
    which quarto >& /dev/null || module load quarto || exit 2
    # Using knitr as an engine, which requires R and the R package knitr
    which R >& /dev/null || module load r-bundle-bioconductor || exit 2
    tempqmdfile="${NAME}-tmp.qmd"
    \cp $tempfile $tempqmdfile
    /usr/bin/time quarto render $tempqmdfile --to beamer --quiet
    \cp ${tempqmdfile/.qmd/.beamer.md} ${tempfile}
    \rm -f ${tempqmdfile} ${tempqmdfile/.qmd/.beamer.md} ${tempqmdfile/.qmd/.pdf}
    +++ quarto done +++
fi

+++ The remaining conversion to latex+beamer is handled by pandoc. +++

if grep -q '^## ' "$tempfile"; then
    SLIDELEVEL="--slide-level 2"
fi

NAME=${NAME}${POSTFIX}

pandoc -t beamer -s ${SLIDELEVEL:-} --highlight-style=$HIGHLIGHT --wrap=none "$tempfile" -o "${NAME}.tex"

if $PLAINTITLE; then
    +++ Removing logo from the title slide +++
    sed -i -e 's/\\frame{\\titlepage}/\\frame[plain]{\\titlepage}/' "${NAME}.tex"
fi

+++ Remove outline numbering if present +++

sed -i -e 's/\[allowframebreaks\]/\[noframenumbering\]/' "${NAME}.tex"

+++ Correct the width of columns environments +++

sed -i -e 's+\\begin{columns}\[T\]+\\begin{columns}[T,totalwidth=\\linewidth]+' "${NAME}.tex"

+++ "${NAME}.tex" created. +++

if $HANDOUT; then
    +++ Making handout version. +++
    sed -i -e 's/]{beamer}/,handout]{beamer}/' ${NAME}.tex
    +++ ${NAME}.tex updated. +++
fi

+++ Fix: let paragraphs in boxes and columns be separated +++

sed -i \
    -e 's/\\begin{block}{\(.*\)}/\\begin{block}{\1}\\setlength{\\parskip}{0.5\\baselineskip}/' \
    -e 's/\\begin{column}{\(.*\)}/\\begin{column}{\1}\\setlength{\\parskip}{0.5\\baselineskip}/' \
    ${NAME}.tex

+++ "Replace placeholders for centering, highlighting, line-skipping" +++
+++ "and add support for overlays extension.                        " +++

sed -i \
    -e 's/SKIPPINGLINE/\\vspace{\\baselineskip}/g' \
    -e 's/BEGINCENTERLINE/\\centerline{/g' \
    -e 's/ENDCENTERLINE/}/g' \
    -e 's/BEGINALERT/\\alert{/g' \
    -e 's/ENDALERT/}/g' \
    -e 's/@ @ @ @/}/g' \
    -e 's/@ @ @ \([0-9][^ ]*\)/\\only<\1>{/g' \
    ${NAME}.tex

+++ ${NAME}.tex updated. +++

+++ Using $ENGINE to convert the latex file to a PDF. +++

if (( VERBOSE < 3 )); then
    REDIR='1>/dev/null'
    QUARTOQUIET=--quiet
else
    REDIR=''
    QUARTOQUIET=''
fi

_INTERMEDIATEFILES+=("${NAME}.nav" "${NAME}.snm" "${NAME}.vrb" "${NAME}.lot" "${NAME}.toc" "${NAME}.aux" "${NAME}.aux.bak" "${NAME}.log" "${NAME}.out" "${NAME}.bbl" "${NAME}.end" "${NAME}.blg" "${NAME}.stdout" "${NAME}.xdv")

if $DRAFT; then
    +++ Update $NAME.tex for a DRAFT version +++
    sed -i \
        -e 's/documentclass\[/documentclass\[draft,/' \
        ${NAME}.tex
    eval ${ENGINE} -halt-on-error -output-directory=$(dirname ${NAME}) ${NAME}.tex $REDIR
else
    +++ First pass: draft version +++
    sed -i \
        -e 's/documentclass\[/documentclass\[draft,/' \
        ${NAME}.tex
    eval ${ENGINE} -halt-on-error -output-directory=$(dirname ${NAME}) ${ENGINEDRAFTMODEOPTION} ${NAME}.tex $REDIR
    +++ Second pass: complete version +++
    sed -i \
        -e 's/documentclass\[draft,/documentclass\[/' \
        ${NAME}.tex
    eval ${ENGINE} -halt-on-error -output-directory=$(dirname ${NAME}) ${NAME}.tex $REDIR
fi

+++ ${NAME}.pdf created. +++



