ASPECTRATIO=169
FONTSIZE=10pt
THEME=Boadilla
INNERTHEME=rounded
FONTTHEME=structurebold
COLORTHEME=orchid
if [ $HANDOUT = true ]
then
    THEMETEX=$HERE/style_handout.tex
    HIGHLIGHT=kate
    LOGO=$HERE/scinetlogo.png
    LOGOHEIGHT=0.12
    LOGOUP=-0.03
else
    THEMETEX=$HERE/style.tex
    HIGHLIGHT=zenburn    
    LOGO=$HERE/scinetlogodark.png
    LOGOHEIGHT=0.15
    LOGOUP=-0.03
fi
