# ---------------------------------------------------------------------
# mds.theme
#
# This file describes the theme configuration settings to be used by
# the markdown-to-slides utility mds.
#
# Syntax:
#  - Lines containing "SETTING=VALUE" (i.e., bash-style assignment)
#  - No spaces are allowed around the equal signs.
#  - VALUEs containing space(s) should be surrounded by quotation marks.
#  - Empty lines and comments starting with # are allowed.
#  - Some bash constructs like "if [ A = B ]" might work.
#
# Lines starting with '#' are comments and otherwise ignored by mds.
#
# Any SETTING that start with THEMETEX_ relies on the implementation in
# the file $THEMETEX (usually mds.tex).
# ---------------------------------------------------------------------
## This file contains the settings for the theme hannover-albatross

# This setting determines the highlight style for code blocks,
#
# Possible values values may depend on the installed version of
# pandoc, but typically are: pygments, tango, espresso, zenburn, kate,
# monochrome, breezedark, haddock
#
# Default value: zenburn
HIGHLIGHT=zenburn

# This setting determines the relative width and height of the slides.
#
# Possible values are: 1610, 169, 149, 54, 43 or 32.
#
# Default value: 169, which means a width:height ratio of 16:9.
ASPECTRATIO=169

# This setting determines the size of the font of the regular text in
# the slides; the font size of the titles will scale accordingly.
#
# Possible values: 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 17pt, 20pt
#
# Default value: 9pt
FONTSIZE=10pt

# This setting selects the overall beamer theme of the slides.
#
# Possible values for themes with numbered sections: AnnArbor,
# Boadilla, CambridgeUS, Copenhagen, Darmstadt, Frankfurt, Ilmenau,
# JuanLesPins, Madrid, PaloAlto, and Warsaw
#
# Possible values for themes with unnumbered sections: Antibes,
# Bergen, Berkeley, Berlin, boxes, default, Dresden, Goettingen,
# Hannover, Luebeck, Malmoe, Marburg, Montpellier, Pittsburgh,
# Rochester, Singapore, and Szeged
#
# Default value: default
THEME=Hannover

# This setting selects the overall beamer color theme of the slides.
#
# Possible values: albatross, beaver, beetle, crane, default, dolphin,
# dove, fly, lily, orchid, rose, seagull, seahorse, sidebartab,
# structure, whale, and wolverine
#
# Default value: default
COLORTHEME=albatross

# This setting determines which file to use to add to the "LaTeX
# preamble". Such a preamble allows a lot of tweaking of the
# style. This file will be read by latex, but usually contains
# parameters that can be set here in the theme file. Note the use of
# $HERE/ which allows points to the same directory as this theme file.
#
# Default value: <empty>
THEMETEX=$HERE/preamble.theme.tex
